
SELECT * FROM raza;

SELECT *FROM tipomascota;
SELECT *FROM mascota;

DELETE FROM mascota;
DELETE FROM raza;
DELETE FROM tipomascota;

ALTER TABLE mascota AUTO_INCREMENT = 1;
ALTER TABLE raza AUTO_INCREMENT = 1;
ALTER TABLE tipomascota AUTO_INCREMENT = 1;